name: Check docs build cleanly

on:
  # And all pull requests
  pull_request:

jobs:
  build_docs:
    name: Run doc build
    # Run on the Github hosted runner
    runs-on: ubuntu-latest
    container:
      image: firedrakeproject/firedrake-vanilla-default:latest
      volumes:
        - ${{ github.workspace }}:/home/firedrake/output
    # Steps represent a sequence of tasks that will be executed as
    # part of the jobs
    steps:
      - name: fix home
        run: echo "HOME=/root" >> "$GITHUB_ENV"
      - uses: actions/checkout@v4
      - name: Install firedrake and dependencies, checkout fuse branches
        run: |
          chmod +x ./.github/workflows/setup_repos.sh
          ./.github/workflows/setup_repos.sh
      - name: Install checkedout fuse
        run: |
          python3 -m pip install --break-system-packages -e '.[docs]'
      - name: Build docs
        run: |
          make docs
