name: Check docs build cleanly

on:
  # Run on pushes to master
  push:
    branches:
      - master
  # And all pull requests
  pull_request:

jobs:
  build_docs:
    name: Run doc build
    # Run on the Github hosted runner
    runs-on: ubuntu-latest
    container:
      image: firedrakeproject/firedrake-docdeps:latest
      # Github hosted runners require running as root user:
      # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#docker-container-filesystem
      options: --user root
      volumes:
        - ${{ github.workspace }}:/home/firedrake/output
    # Steps represent a sequence of tasks that will be executed as
    # part of the jobs
    steps:
      - uses: actions/checkout@v4
      - name: Install checkedout redefining_fe
        run: |
          . /home/firedrake/firedrake/bin/activate
          python -m pip install -e .

      - name: Build docs
        run: |
          . /home/firedrake/firedrake/bin/activate
          cd docs
          make html SPHINXOPTS="-W --keep-going -n"
          
