name: Run tests
# I stole this from the main firedrake repo

on:
#   # Run on pushes to main
    push:
        branches:
        - main
#   # And all pull requests
    pull_request:

concurrency:
  # Cancel running jobs if new commits are pushed
  group: >
    ${{ github.workflow }}-
    ${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  OMPI_ALLOW_RUN_AS_ROOT: 1
  OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1
  OMP_NUM_THREADS: 1
  OPENBLAS_NUM_THREADS: 1
  PYTEST_MPI_MAX_NPROCS: 8
  PYOP2_SPMD_STRICT: 1
  FIREDRAKE_CI: 1
  FIREDRAKE_USE_FUSE: 1
  # NOTE: One should occasionally update test_durations.json by running
  # 'make test_durations' inside a 'firedrake:latest' Docker image.
  EXTRA_PYTEST_ARGS: --splitting-algorithm least_duration --timeout=600 --timeout-method=thread -o faulthandler_timeout=660


jobs:
  test:
    name: Test
    runs-on: [self-hosted, Linux]
    container:
      image: ubuntu:latest
    env:
      # Disable some compiler optimisations as they cause runner-specific bugs
      PYOP2_CFLAGS: -O1 -fno-fast-math
    steps:
      - name: Pre-run cleanup
        # Make sure the current directory is empty
        run: find . -delete

      - uses: actions/checkout@v5
        with:
          path: firedrake-repo
          ref: refs/heads/connorjward/pyop3-develop

      - name: Install Firedrake
        id: install
        uses: ./firedrake-repo/.github/actions/install
        with:
          os: linux
          source_ref: refs/heads/connorjward/pyop3-develop
          base_ref: main
          deps: ci

      - uses: actions/checkout@v5
        with:
          repository: firedrakeproject/firedrake
          path: firedrake-repo
          ref: refs/heads/indiamai/fuse-closures-with-pyop3
    
      - name: Make cython
        run: |
          . venv/bin/activate
          cd ./firedrake-repo
          make
    
      - uses: actions/checkout@v5
        with:
          path: fuse-repo
    
      - name: Install checked out fuse
        run: |
          . venv/bin/activate
          python3 -m pip install --break-system-packages -e './fuse-repo[dev]'
    
      - uses: actions/checkout@v5
        with:
          repository: firedrakeproject/fiat
          path: fiat-repo
          ref: refs/heads/indiamai/integrate_fuse
        
      - name: Install checked out FIAT
        run: |
          . venv/bin/activate
          python3 -m pip install --break-system-packages -e './fiat-repo'

      - name: Run tests
        run: |
          . venv/bin/activate
          cd ./fuse-repo
          firedrake-run-split-tests 1 1 -n 8 "$EXTRA_PYTEST_ARGS" ./test